name: Generate Snake Animation

on:
  schedule:
    # Runs at midnight UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: rochdi7
          outputs: dist/snake.svg

      # Commit and push the generated snake.svg
      - name: Push Snake Animation
        run: |
          mkdir -p dist
          mv dist/snake.svg .github/workflows/snake.svg
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .github/workflows/snake.svg
          git commit -m "Updated snake animation"
          git push
